# Generated by Django 5.2.8 on 2026-01-09 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('calle_y_numero', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad_o_municipio', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BR', 'Brincolín'), ('ME', 'Mesa'), ('SI', 'Silla'), ('AN', 'Animación'), ('FL', 'Flete'), ('LZ', 'Loza'), ('MT', 'Manteleria'), ('OT', 'Otro')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_total', models.PositiveIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_renta', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('calle_y_numero', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad_o_municipio', models.CharField(blank=True, max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('cargador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('renta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finanza', to='core.renta')),
            ],
        ),
        migrations.CreateModel(
            name='RentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentaproductos', to='core.producto')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentaproductos', to='core.renta')),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='productos',
            field=models.ManyToManyField(through='core.RentaProducto', to='core.producto'),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Creada', 'Creada'), ('EN_RUTA', 'En ruta'), ('FINALIZADA', 'Finalizada')], default='Creada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas', to='core.ruta'),
        ),
        migrations.CreateModel(
            name='OcupacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('PARCIAL', 'Parcial'), ('LLENO', 'Lleno')], max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='core_ocupac_fecha_4f74fb_idx'), models.Index(fields=['producto', 'fecha'], name='core_ocupac_product_a077a4_idx')],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
