# Generated by Django 5.2.8 on 2026-01-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('calle_y_numero', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad_o_municipio', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('banco', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sueldo_diario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_empleado', models.CharField(choices=[('REPARTIDOR', 'Repartidor'), ('SOCIO', 'Socio'), ('ENCARGADO', 'Encargado de Material')], default='REPARTIDOR', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('BR', 'Brincolín'), ('ME', 'Mesa'), ('SI', 'Silla'), ('AN', 'Animación'), ('FL', 'Flete'), ('LZ', 'Loza'), ('MT', 'Manteleria'), ('OT', 'Otro')], max_length=2)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_total', models.PositiveIntegerField(default=0)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_default', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='HorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField()),
                ('semana_fin', models.DateField(editable=False)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pago_hora', models.DecimalField(decimal_places=2, default=55, max_digits=8)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_trabajados', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTO', 'Gasto General'), ('COMPRA', 'Compra'), ('NOMINA', 'Nómina')], max_length=10)),
                ('categoria', models.CharField(choices=[('INSUMOS', 'Insumos'), ('GASOLINA', 'Gasolina'), ('REFACCIONES', 'Refacciones'), ('CONSUMIBLES', 'Consumibles'), ('SEGURO', 'Seguro'), ('IMPUESTOS', 'Impuestos')], default='INSUMOS', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuenta')),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='core.nomina')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('metodo_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoFinanzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cuenta')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='core.pedidofinanzas')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_renta', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_renta', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('calle_y_numero', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad_o_municipio', models.CharField(blank=True, max_length=100)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recolectado', models.BooleanField(default=False)),
                ('Fecha_Recoleccion', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('cargador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('recolectado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recolecciones', to='core.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='pedidofinanzas',
            name='renta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finanza', to='core.renta'),
        ),
        migrations.CreateModel(
            name='RentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentaproductos', to='core.producto')),
                ('renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentaproductos', to='core.renta')),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='productos',
            field=models.ManyToManyField(through='core.RentaProducto', to='core.producto'),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Creada', 'Creada'), ('EN_RUTA', 'En ruta'), ('FINALIZADA', 'Finalizada')], default='Creada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas', to='core.ruta'),
        ),
        migrations.CreateModel(
            name='PagoExtraNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_extras', to='core.nomina')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopagoextra')),
            ],
        ),
        migrations.CreateModel(
            name='OcupacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('PARCIAL', 'Parcial'), ('LLENO', 'Lleno')], max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='core_ocupac_fecha_4f74fb_idx'), models.Index(fields=['producto', 'fecha'], name='core_ocupac_product_a077a4_idx')],
                'unique_together': {('producto', 'fecha')},
            },
        ),
    ]
