# Generated by Django 5.2.8 on 2026-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('Banco', 'Cuenta bancaria'), ('Efectivo', 'Efectivo / Caja')], default='Banco', max_length=10),
        ),
    ]
