# Generated by Django 6.0.3 on 2026-03-22 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuenta_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAnimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('REUTILIZABLE', 'Reutilizable'), ('CONSUMIBLE', 'Consumible')], default='REUTILIZABLE', max_length=20)),
                ('stock_total', models.PositiveIntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='materiales/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL)),
                ('renta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_coordinador', to='core.renta')),
            ],
            options={
                'verbose_name': 'Asignacion Coordinador',
            },
        ),
        migrations.CreateModel(
            name='MaterialEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.asignacioncoordinador')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='core.materialanimacion')),
            ],
            options={
                'verbose_name': 'Material del Evento',
                'unique_together': {('asignacion', 'material')},
            },
        ),
    ]
