# Generated by Django 5.2.8 on 2026-01-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empleado_nomina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomina',
            old_name='eventos_extras',
            new_name='eventos_extra',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='pago_extra_por_evento',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='total',
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('GASTO', 'Gasto General'), ('COMPRA', 'Compra'), ('NOMINA', 'Nómina')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomina',
            name='pago_evento_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sueldo_diario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado'),
        ),
    ]
