# Generated by Django 5.2.8 on 2026-01-02 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra_gasto_pedidofinanzas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='cargador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
