# Generated by Django 5.2.8 on 2026-01-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_eventos_extras_nomina_eventos_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='eventos_extra',
        ),
        migrations.AddField(
            model_name='nomina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='dias_trabajados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='pago_evento_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
