# Generated by Django 5.2.8 on 2026-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_renta_cargador'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
