# Generated by Django 5.2.8 on 2026-01-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_renta_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='estado_entrega',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='ASIGNADO', max_length=15),
        ),
    ]
