# Generated by Django 6.0.3 on 2026-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_listamaterialevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialanimacion',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
