# Generated by Django 6.0.3 on 2026-04-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_materialanimacion_stock_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='materiales/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.materialanimacion')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
    ]
