# Generated by Django 5.2.8 on 2026-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_renta_estado_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15),
        ),
    ]
