# Generated by Django 5.2.8 on 2026-01-04 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_renta_estado_entrega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='estado_entrega',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN_RUTA', 'En ruta'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Creada', 'Creada'), ('EN_RUTA', 'En ruta'), ('FINALIZADA', 'Finalizada')], default='Creada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cargador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='renta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentas', to='core.ruta'),
        ),
    ]
