# Generated by Django 5.2.10 on 2026-06-06 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fotomaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listamaterialevento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialanimacion',
            options={'ordering': ('nombre',), 'verbose_name': 'Material de Animación', 'verbose_name_plural': 'Materiales de Animación'},
        ),
        migrations.RemoveField(
            model_name='listamaterialevento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listamaterialevento',
            name='notas_encargado',
        ),
        migrations.RemoveField(
            model_name='listamaterialevento',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='observaciones_recepcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='recibida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialevento',
            name='despachado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialevento',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialevento',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialevento',
            name='stock_restaurado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('GASOLINA', 'Gasolina'), ('REFACCIONES', 'Refacciones'), ('CONSUMIBLES', 'Consumibles'), ('SEGURO', 'Seguro'), ('IMPUESTOS', 'Impuestos'), ('NOMINA', 'Nómina')], default='INSUMOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='listamaterialevento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente revisión'), ('REVISADA', 'Revisada'), ('PREPARADA', 'Preparada'), ('RECIBIDA', 'Recibida')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['fecha', 'tipo'], name='core_movimi_fecha_3be2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['cuenta', 'tipo'], name='core_movimi_cuenta__bfc5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['empleado', 'fecha_inicio'], name='core_nomina_emplead_3b7299_idx'),
        ),
        migrations.AddIndex(
            model_name='nomina',
            index=models.Index(fields=['fecha_fin'], name='core_nomina_fecha_f_64229b_idx'),
        ),
        migrations.AddIndex(
            model_name='renta',
            index=models.Index(fields=['fecha_renta', 'status'], name='core_renta_fecha_r_c846e5_idx'),
        ),
        migrations.AddIndex(
            model_name='renta',
            index=models.Index(fields=['status', 'pagado'], name='core_renta_status_d4d2be_idx'),
        ),
        migrations.AddIndex(
            model_name='renta',
            index=models.Index(fields=['estado_entrega'], name='core_renta_estado__1a24c2_idx'),
        ),
        migrations.AddIndex(
            model_name='renta',
            index=models.Index(fields=['cliente'], name='core_renta_cliente_134832_idx'),
        ),
    ]
