# Generated by Django 5.2.10 on 2026-06-07 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_listamaterialevento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_entrada', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_salida', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_jornada', models.CharField(choices=[('COMPLETA', 'Jornada completa'), ('MEDIO_TIEMPO', 'Medio tiempo'), ('EVENTO', 'Por evento')], default='COMPLETA', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='core_asiste_emplead_5f4bae_idx'), models.Index(fields=['fecha'], name='core_asiste_fecha_8684f2_idx')],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
