# Generated by Django 5.2.10 on 2026-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_eventual',
            field=models.BooleanField(default=False, verbose_name='Empleado eventual'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_empleado',
            field=models.CharField(choices=[('REPARTIDOR', 'Repartidor'), ('COORDINADOR', 'Coordinador'), ('ENCARGADO', 'Encargado de Material'), ('ANIMADOR', 'Animador')], default='REPARTIDOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='tipo_empleado',
            field=models.CharField(choices=[('REPARTIDOR', 'Repartidor'), ('COORDINADOR', 'Coordinador'), ('ENCARGADO', 'Encargado de Material'), ('ANIMADOR', 'Animador')], default='REPARTIDOR', max_length=20),
        ),
    ]
