# Generated by Django 5.2.10 on 2026-06-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_empleado_es_eventual_alter_empleado_tipo_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopagoextra',
            name='descuenta_horas',
            field=models.BooleanField(default=False, verbose_name='Descuenta horas del empleado'),
        ),
        migrations.AddField(
            model_name='tipopagoextra',
            name='horas_a_descontar',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=4, verbose_name='Horas a descontar'),
        ),
    ]
