# Generated by Django 5.2.10 on 2026-06-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tipopagoextra_descuenta_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasextra',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horasextra',
            name='horas_computables',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='horasextra',
            name='horas_descontadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='horasextra',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
