# Generated by Django 5.2.10 on 2026-06-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_horasextra_fecha_pago_horasextra_horas_computables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_confirmada', models.PositiveSmallIntegerField(default=0)),
                ('motores_dejados', models.PositiveSmallIntegerField(default=0)),
                ('extensiones_dejadas', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Detalle de entrega',
                'verbose_name_plural': 'Detalles de entrega',
            },
        ),
        migrations.CreateModel(
            name='RecogidaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recogida', models.DateField()),
                ('tipo_horario', models.CharField(choices=[('fijo', 'Hora fija'), ('rango', 'Rango de horas')], default='rango', max_length=5)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recogida programada',
                'verbose_name_plural': 'Recogidas programadas',
            },
        ),
        migrations.CreateModel(
            name='RutaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_lider', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado en ruta',
                'verbose_name_plural': 'Empleados en ruta',
            },
        ),
        migrations.CreateModel(
            name='RutaRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado'), ('recogido', 'Recogido')], default='pendiente', max_length=15)),
                ('hora_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notas_campo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parada de ruta',
                'verbose_name_plural': 'Paradas de ruta',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-fecha', 'nombre'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.RenameField(
            model_name='ruta',
            old_name='created_at',
            new_name='creada_en',
        ),
        migrations.RemoveField(
            model_name='renta',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='cargador',
        ),
        migrations.AddField(
            model_name='ruta',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(default='Ruta', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruta',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('entrega', 'Entrega'), ('recogida', 'Recogida')], default='entrega', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_camino', 'En camino'), ('completada', 'Completada')], default='pendiente', max_length=15),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['fecha', 'estado'], name='core_ruta_fecha_2a1342_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['tipo', 'estado'], name='core_ruta_tipo_2c35b5_idx'),
        ),
        migrations.AddField(
            model_name='entregadetalle',
            name='producto_renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='core.rentaproducto'),
        ),
        migrations.AddField(
            model_name='rutaempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='core.empleado'),
        ),
        migrations.AddField(
            model_name='rutaempleado',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.ruta'),
        ),
        migrations.AddField(
            model_name='rutarenta',
            name='renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='core.renta'),
        ),
        migrations.AddField(
            model_name='rutarenta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='core.ruta'),
        ),
        migrations.AddField(
            model_name='recogidaprogramada',
            name='ruta_renta_entrega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recogida_programada', to='core.rutarenta'),
        ),
        migrations.AddField(
            model_name='entregadetalle',
            name='ruta_renta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.rutarenta'),
        ),
        migrations.AlterUniqueTogether(
            name='rutaempleado',
            unique_together={('ruta', 'empleado')},
        ),
        migrations.AddIndex(
            model_name='rutarenta',
            index=models.Index(fields=['estado'], name='core_rutare_estado_c9bef6_idx'),
        ),
        migrations.AddIndex(
            model_name='recogidaprogramada',
            index=models.Index(fields=['fecha_recogida'], name='core_recogi_fecha_r_1645c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entregadetalle',
            unique_together={('ruta_renta', 'producto_renta')},
        ),
    ]
