# Generated by Django 5.2.10 on 2026-06-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pushsuscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.PositiveSmallIntegerField(default=1)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_entrada', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_salida', models.CharField(blank=True, max_length=255, null=True)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.asistencia')),
            ],
            options={
                'verbose_name': 'Turno de asistencia',
                'verbose_name_plural': 'Turnos de asistencia',
                'ordering': ['numero_turno'],
                'unique_together': {('asistencia', 'numero_turno')},
            },
        ),
    ]
