# Generated by Django 5.2.10 on 2026-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_turnoasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='evento_google_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
