# Generated by Django 5.2.10 on 2026-06-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_renta_evento_google_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterialevento',
            name='confirmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='fecha_surtido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='llego_completa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='observaciones_llegada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listamaterialevento',
            name='surtida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_surtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listamaterialevento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada a encargado'), ('SURTIDA', 'Surtida por encargado'), ('EN_EVENTO', 'En evento'), ('REGRESADA', 'Regresada a bodega'), ('REVISADA', 'Revisada'), ('PENDIENTE', 'Pendiente revisión'), ('PREPARADA', 'Preparada'), ('RECIBIDA', 'Recibida')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='EvidenciaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida a evento'), ('LLEGADA', 'Llegada a evento'), ('REGRESO', 'Regreso a bodega'), ('DANO', 'Daño o faltante')], max_length=20)),
                ('foto', models.ImageField(upload_to='evidencias_material/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.listamaterialevento')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
