# Generated by Django 5.2.10 on 2026-06-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_listamaterialevento_confirmada_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente confirmación'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('hora_cita', models.TimeField(blank=True, null=True)),
                ('tipo_llegada', models.CharField(blank=True, choices=[('BODEGA', 'Llego a bodega'), ('LOCAL', 'Llego al local')], max_length=10, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_animador', to='core.empleado')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animadores', to='core.asignacioncoordinador')),
            ],
            options={
                'unique_together': {('asignacion', 'animador')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionCoordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('organizacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('trato', models.DecimalField(decimal_places=1, max_digits=3)),
                ('respeto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('puntualidad', models.DecimalField(decimal_places=1, max_digits=3)),
                ('innovacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('animador_evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='core.animadorevento')),
            ],
        ),
    ]
