# Generated by Django 5.2.10 on 2026-06-17 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_animadorevento_calificacioncoordinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionAnimador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proactividad', models.DecimalField(decimal_places=1, max_digits=3)),
                ('disposicion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('puntualidad', models.DecimalField(decimal_places=1, max_digits=3)),
                ('compromiso', models.DecimalField(decimal_places=1, max_digits=3)),
                ('respeto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('atencion_clientes', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('animador_evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_coordinador', to='core.animadorevento')),
            ],
        ),
    ]
