# Generated by Django 5.2.17 on 2026-08-08 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_whatsapp_message_buffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitioWebContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido sitio web',
                'verbose_name_plural': 'Contenido sitio web',
            },
        ),
        migrations.CreateModel(
            name='SitioWebMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('imagen', models.ImageField(upload_to='sitio/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen sitio web',
                'verbose_name_plural': 'Imágenes sitio web',
            },
        ),
        migrations.AlterModelOptions(
            name='materialanimacion',
            options={'ordering': ('nombre',), 'verbose_name': 'Material de Animaci?n', 'verbose_name_plural': 'Materiales de Animaci?n'},
        ),
        migrations.AlterModelOptions(
            name='presupuestocategoria',
            options={'ordering': ['categoria'], 'verbose_name': 'Presupuesto por categor?a', 'verbose_name_plural': 'Presupuestos por categor?a'},
        ),
        migrations.AlterModelOptions(
            name='pushsuscripcion',
            options={'verbose_name': 'Suscripci?n Push', 'verbose_name_plural': 'Suscripciones Push'},
        ),
        migrations.RenameIndex(
            model_name='cotizacion',
            new_name='core_cotiza_tipo_2ea79e_idx',
            old_name='core_cotiza_tipo_st_idx',
        ),
        migrations.RenameIndex(
            model_name='cotizacion',
            new_name='core_cotiza_fecha_e_77af1f_idx',
            old_name='core_cotiza_fecha_e_idx',
        ),
        migrations.RenameIndex(
            model_name='factura',
            new_name='core_factur_renta_i_a97970_idx',
            old_name='core_factur_renta_i_idx',
        ),
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='animadorevento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente confirmaci?n'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidenciamaterial',
            name='tipo',
            field=models.CharField(choices=[('SALIDA', 'Salida a evento'), ('LLEGADA', 'Llegada a evento'), ('REGRESO', 'Regreso a bodega'), ('DANO', 'Da?o o faltante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('GASOLINA', 'Gasolina'), ('REFACCIONES', 'Refacciones'), ('CONSUMIBLES', 'Consumibles'), ('SEGURO', 'Seguro'), ('IMPUESTOS', 'Impuestos'), ('NOMINA', 'N?mina'), ('DEVOLUCION', 'Devoluci?n dep?sito')], default='INSUMOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('GASTO', 'Gasto General'), ('COMPRA', 'Compra'), ('NOMINA', 'N?mina')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listamaterialevento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada a encargado'), ('SURTIDA', 'Surtida por encargado'), ('EN_EVENTO', 'En evento'), ('REGRESADA', 'Regresada a bodega'), ('REVISADA', 'Revisada'), ('PENDIENTE', 'Pendiente revisi?n'), ('PREPARADA', 'Preparada'), ('RECIBIDA', 'Recibida')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='presupuestocategoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si est? inactivo, no se valida presupuesto para esta categor?a.'),
        ),
        migrations.AlterField(
            model_name='presupuestocategoria',
            name='categoria',
            field=models.CharField(choices=[('INSUMOS', 'Insumos'), ('GASOLINA', 'Gasolina'), ('REFACCIONES', 'Refacciones'), ('CONSUMIBLES', 'Consumibles'), ('SEGURO', 'Seguro'), ('IMPUESTOS', 'Impuestos'), ('NOMINA', 'N?mina'), ('DEVOLUCION', 'Devoluci?n dep?sito')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='presupuestocategoria',
            name='monto_mensual',
            field=models.DecimalField(decimal_places=2, help_text='L?mite de gasto permitido en el mes calendario.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('BR', 'Brincol?n'), ('ME', 'Mesa'), ('SI', 'Silla'), ('AN', 'Animaci?n'), ('FL', 'Flete'), ('LZ', 'Loza'), ('MT', 'Manteleria'), ('OT', 'Otro')], max_length=2),
        ),
        migrations.AddField(
            model_name='sitiowebcontenido',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitio_web_ediciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
