"""
Django settings for crm_trota project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-for-dev')
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.SessionExpiradaMiddleware',  # ← después de AuthenticationMiddleware
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'crm_trota.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_trota.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local: por defecto SQLite (db.sqlite3).
# Producción: define POSTGRES_DB (y usuario/clave/host) o USE_POSTGRES=true
# con las mismas variables; en el servidor ejecuta migrate con esa .env.

if os.environ.get("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR / 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ============================
# SESSION TIMEOUT (PRODUCCIÓN)
# ============================

SESSION_COOKIE_AGE = 30 *60  # 30 minutos
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ============================
# LOGGING
# ============================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/crm.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ── Seguridad: headers manejados por Nginx, desactivar en Django ──
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
# X_FRAME_OPTIONS = None
SECURE_REFERRER_POLICY = None

# ── Django REST Framework ─────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'public': '60/min',
    },
}

# ── JWT Configuration ─────────────────────────────────────────────────
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ── CORS ─────────────────────────────────────────────────────────────
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:4173',
    'http://localhost:5174',
    'https://app.trotacrm.com',
    'https://trotacrm.com',
    'https://www.trotacrm.com',
]
CORS_ALLOW_CREDENTIALS = True
# Webhook n8n para avisar al cliente (aprobar/rechazar logistica desde CRM)
BOT_NOTIFY_WEBHOOK_URL = os.environ.get(
    'BOT_NOTIFY_WEBHOOK_URL',
    'https://bot.app.trotacrm.com/webhook/bot-notify-cliente',
)

# ── WhatsApp Cloud API (Meta) ─────────────────────────────────────────
# Webhook: GET/POST https://app.trotacrm.com/v1/bot/whatsapp-meta/
META_WA_VERIFY_TOKEN = os.environ.get('META_WA_VERIFY_TOKEN', 'trota-wa-verify')
META_WA_ACCESS_TOKEN = os.environ.get('META_WA_ACCESS_TOKEN', '')
META_WA_PHONE_NUMBER_ID = os.environ.get('META_WA_PHONE_NUMBER_ID', '')
META_WA_GRAPH_VERSION = os.environ.get('META_WA_GRAPH_VERSION', 'v21.0')
META_WA_N8N_FORWARD_URL = os.environ.get(
    'META_WA_N8N_FORWARD_URL',
    'https://bot.app.trotacrm.com/webhook/whatsapp',
)
META_WA_DISPLAY_NUMBER = os.environ.get('META_WA_DISPLAY_NUMBER', '523121529952')

# ── YCloud (BSP WhatsApp) ─────────────────────────────────────────────
YCLOUD_API_KEY = os.environ.get('YCLOUD_API_KEY', '')
YCLOUD_API_BASE = os.environ.get('YCLOUD_API_BASE', 'https://api.ycloud.com/v2')
# E.164 del número conectado en YCloud (MX móvil WA: +521…)
YCLOUD_FROM_NUMBER = os.environ.get('YCLOUD_FROM_NUMBER', '+5213121529952')
# Segundos desde el primer mensaje del lote antes de reenviar a n8n (0 = inmediato)
WA_DEBOUNCE_SECONDS = int(os.environ.get('WA_DEBOUNCE_SECONDS', '5') or '5')

# ── Dominio público (usado para armar links absolutos, ej. proxy de media) ──
PUBLIC_BASE_URL = os.environ.get('PUBLIC_BASE_URL', 'https://app.trotacrm.com')
# Horas de vida del link firmado que ve el asesor para abrir comprobantes (YCloud
# retiene el archivo original ~30 días de su lado; esto solo acorta la ventana
# de exposición del link, no necesita acercarse a ese límite).
WA_MEDIA_PROXY_MAX_AGE_HOURS = int(os.environ.get('WA_MEDIA_PROXY_MAX_AGE_HOURS', '168') or '168')

# ── Anthropic (extracción de intención/slots del bot WhatsApp) ────────
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
ANTHROPIC_MODEL = os.environ.get('ANTHROPIC_MODEL', 'claude-sonnet-5')
# Segundos antes de abortar la llamada y caer al fallback (menú de siempre)
ANTHROPIC_TIMEOUT_S = float(os.environ.get('ANTHROPIC_TIMEOUT_S', '8') or '8')

# ── FiscalAPI (CFDI) ──────────────────────────────────────────────────
# Sandbox: https://test.fiscalapi.com  |  Prod: https://live.fiscalapi.com
FISCALAPI_BASE_URL = os.environ.get('FISCALAPI_BASE_URL', 'https://test.fiscalapi.com')
FISCALAPI_API_KEY = os.environ.get('FISCALAPI_API_KEY', '')
FISCALAPI_TENANT_KEY = os.environ.get('FISCALAPI_TENANT_KEY', '')
FISCALAPI_ISSUER_ID = os.environ.get('FISCALAPI_ISSUER_ID', '')
FISCALAPI_EXPEDITION_ZIP = os.environ.get('FISCALAPI_EXPEDITION_ZIP', '')
FISCALAPI_SERIES = os.environ.get('FISCALAPI_SERIES', 'R')
# ClaveProdServ y unidad fijas en facturacion.py: 90101602 / E48 Servicio
FISCALAPI_TAX_RATE = os.environ.get('FISCALAPI_TAX_RATE', '0.160000')
FISCALAPI_ISR_RETENTION_RATE = os.environ.get('FISCALAPI_ISR_RETENTION_RATE', '0.012500')
# false = precio_total del CRM es subtotal ANTES de IVA (comportamiento Trotamundos)
FISCALAPI_TOTAL_INCLUDES_TAX = os.environ.get('FISCALAPI_TOTAL_INCLUDES_TAX', 'false')
FISCALAPI_PAYMENT_FORM = os.environ.get('FISCALAPI_PAYMENT_FORM', '03')
FISCALAPI_TIMEZONE = os.environ.get('FISCALAPI_TIMEZONE', 'America/Mexico_City')
# Copia de cada factura timbrada (además del correo del cliente, si lo hay)
FISCALAPI_COPY_EMAIL = os.environ.get('FISCALAPI_COPY_EMAIL', '')
